<a href="https://colab.research.google.com/github/nreddyabhinav/ML/blob/master/Python_Notebooks/tensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install -q pyyaml  # Required to save models in YAML format

In [2]:
from google.colab import drive

drive.mount("/content/drive")


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [3]:
import tensorflow as tf
from tensorflow.keras import layers

print(tf.VERSION)
print(tf.keras.__version__)

1.14.0-rc1
2.2.4-tf


In [4]:
model = tf.keras.Sequential([
# Adds a densely-connected layer with 64 units to the model:
layers.Dense(400, activation='relu', input_shape=(400,)),
# Add another:
layers.Dense(25, activation='relu'),
# Add a softmax layer with 10 output units:
layers.Dense(10, activation='softmax')])

model.compile(optimizer=tf.train.AdamOptimizer(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

W0614 21:56:34.555477 140485322786688 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [5]:
import numpy as np
from scipy.io import loadmat


data = loadmat('drive/My Drive/ColabNo/nn/ex4data1.mat')

x = np.array(data['X'])
y = np.array(data['y'])



#splitting the data

count = np.zeros(np.max(y))

a=[]
b=[]
c=[]
d=[]
for i in range(0,len(y)):
  if(count[y[i]-1]<350):
    a.append(x[i])
    b.append(y[i])
    count[y[i]-1] = count[y[i]-1]+1
  else:
    c.append(x[i])
    d.append(y[i])
    
x=np.array(a)
y=np.array(b)
xtest=np.array(c)
ytest=np.array(d)


highest = max(y)[0]
Y = np.zeros((1,highest))
for i in y:
  temp = np.zeros((1,highest))
  temp[0][i[0]-1]=1
#   print(temp)
  Y = np.concatenate((Y,temp),axis=0)

Y= Y[1:]

#changing test y data to a vector

print(ytest[1000:1005])
highest = max(ytest)[0]
Ytest = np.zeros((1,highest))
for i in ytest:
  temp = np.zeros((1,highest))
  temp[0][i[0]-1]=1
#   print(temp)
  Ytest = np.concatenate((Ytest,temp),axis=0)

Ytest= Ytest[1:]

print(Ytest[1000:1005])


[[6]
 [6]
 [6]
 [6]
 [6]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [10]:


data = x
labels = Y

val_data = xtest
val_labels = Ytest

dataset = tf.data.Dataset.from_tensor_slices((data,labels))
dataset = dataset.batch(35).repeat()
val_dataset = tf.data.Dataset.from_tensor_slices((val_data,val_labels)).batch(15).repeat()


model.fit(dataset,epochs=10,steps_per_epoch=100,validation_data=val_dataset,validation_steps=100)

W0614 21:57:40.421068 140485322786688 training_utils.py:1300] Expected a shuffled dataset but input dataset `x` is not shuffled. Please invoke `shuffle()` on input dataset.


Epoch 1/10
100/100 [==============================] - 1s 5ms/step - loss: 0.0612 - acc: 0.9866 - val_loss: 0.2231 - val_acc: 0.9360
Epoch 2/10
100/100 [==============================] - 0s 4ms/step - loss: 0.0516 - acc: 0.9897 - val_loss: 0.2198 - val_acc: 0.9367
Epoch 3/10
100/100 [==============================] - 0s 4ms/step - loss: 0.0426 - acc: 0.9920 - val_loss: 0.2164 - val_acc: 0.9380
Epoch 4/10
100/100 [==============================] - 0s 4ms/step - loss: 0.0357 - acc: 0.9929 - val_loss: 0.2149 - val_acc: 0.9420
Epoch 5/10
100/100 [==============================] - 0s 4ms/step - loss: 0.0297 - acc: 0.9940 - val_loss: 0.2129 - val_acc: 0.9413
Epoch 6/10
100/100 [==============================] - 0s 4ms/step - loss: 0.0250 - acc: 0.9960 - val_loss: 0.2132 - val_acc: 0.9420
Epoch 7/10
100/100 [==============================] - 0s 4ms/step - loss: 0.0215 - acc: 0.9963 - val_loss: 0.2114 - val_acc: 0.9413
Epoch 8/10
100/100 [==============================] - 0s 4ms/step - loss: 0.

In [11]:
model.evaluate(val_dataset,steps=100)

100/100 [==============================] - 0s 2ms/step - loss: 0.2140 - acc: 0.9453


[0.21397183475419296, 0.94533336]

In [0]:
res=model.predict(xtest,batch_size=15)

In [17]:
print(res[0])
print(Ytest[0])

[5.2825040e-13 2.5797469e-09 4.1918731e-09 4.4508904e-11 3.7175360e-07
 4.0870535e-08 8.8356621e-11 1.6515552e-08 2.3961061e-06 9.9999714e-01]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
